services:
  db:
    image: postgres:latest
    container_name: crypto_postgres_db
    environment:
      POSTGRES_USER: crypto
      POSTGRES_PASSWORD: cryptocrypto
      POSTGRES_DB: Crypto_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
