"""migration message

Revision ID: c00532cc0ebe
Revises: 
Create Date: 2024-11-06 10:21:29.963581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c00532cc0ebe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('crypto_wallets_wallet_id_fkey', 'crypto_wallets', type_='foreignkey')

    op.drop_index('ix_cookies_email', table_name='cookies')
    op.drop_index('ix_cookies_id', table_name='cookies')
    op.drop_table('cookies')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_crypto_wallets_id', table_name='crypto_wallets')
    op.drop_table('crypto_wallets')
    op.drop_index('ix_co_email', table_name='co')
    op.drop_index('ix_co_id', table_name='co')
    op.drop_table('co')
    

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('co',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('wallet_connected', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='co_pkey')
    )
    op.create_index('ix_co_id', 'co', ['id'], unique=False)
    op.create_index('ix_co_email', 'co', ['email'], unique=True)
    op.create_table('crypto_wallets',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('wallet_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('wallet_balance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wallet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['users.id'], name='crypto_wallets_wallet_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'wallet_address', name='crypto_wallets_pkey')
    )
    op.create_index('ix_crypto_wallets_id', 'crypto_wallets', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wallet_connected', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('cookies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('wallet_connected', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cookies_pkey')
    )
    op.create_index('ix_cookies_id', 'cookies', ['id'], unique=False)
    op.create_index('ix_cookies_email', 'cookies', ['email'], unique=True)
    # ### end Alembic commands ###
